repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix]
        files: ^(app|tools|tests|ui)/
      - id: ruff-format
        name: ruff (format)
        files: ^(app|tools|tests|ui)/

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^(app|tools|tests|ui)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        files: ^(app|tools)/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit - security linter
        args: ["-c", "bandit.yaml", "-q", "-r", "app", "tools"]
        files: ^(app|tools)/

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest (quick)
        entry: bash -c '[[ "${FAST_TESTS:-1}" = "0" ]] && exit 0 || pytest -q -k "not slow"'
        language: system
        pass_filenames: false
        files: ^(app|tools|tests)/

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
        name: markdownlint
        files: ^(README\.md|docs/.*\.md)$
        args: ["--config", ".markdownlint.jsonc"]
