name: KB Sync + Index
on:
  pull_request:
    paths:
      - "knowledge_base/**"
      - "tools/**"
      - ".github/workflows/kb.yml"
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Sync external KB
        run: make kb-sync
      - name: Build & Index
        run: make kb-build kb-index
      - name: Validate Traceability
        run: make kb-validate
