name: labels-sync
on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/labels-sync.yml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
